@echo off
echo updating registry
reg add "HKCU\Software\Wine\DllOverrides" /v "FAudio" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_10" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_8" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_9" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
timeout.exe 10 /nobreak >NUL 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "FAudio" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "x3daudio1_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "X3DAudio1_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_10" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_8" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine2_9" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "xactengine3_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAPOFX1_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_0" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_1" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_2" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_3" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_4" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_5" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_6" /t REG_SZ /d "builtin,native" /f >nul 2>&1
reg add "HKCU\Software\Wine\DllOverrides" /v "XAudio2_7" /t REG_SZ /d "builtin,native" /f >nul 2>&1